### ISSUE TITLE
--show_3d might not be working on rasberry pi?

### ISSUE THREAD

**Issue by corlangerak** [geaxgx/depthai_blazepose#3]
Hi sorry to bother again.
Thank you for your previous help and quick replies, now --show_3d is working amazingly on my Mac and I am very happy about it.
Now I tried to run it on my rasberry pi 4B. I have opencv and all the depthai dependencies installed. I also installed your requirements.txt file.

However when running the BlazeposeDepthai.py script with -3 / --show_3d I get the following error:

`python3 BlazeposeDepthai.py -3
/home/pi/.virtualenvs/cv-installatie/lib/python3.7/site-packages/open3d/__init__.py:21: UserWarning: failed to import module _transformations
  warnings.warn('failed to import module %s' % name)
896 anchors have been created
Traceback (most recent call last):
  File "BlazeposeDepthai.py", line 610, in <module>
    internal_fps=args.internal_fps)
  File "BlazeposeDepthai.py", line 166, in __init__
    self.vis3d = o3d.visualization.Visualizer()
AttributeError: module 'open3d' has no attribute 'visualization'
` 

If I run it without it works fine. Is this not possible on a rasberry pi? or am I missing something?
Thank you for your time and this great Repo!

**Comment by geaxgx** [comment]
I am not familiar with raspberry pi, but from the note there: https://github.com/luxonis/depthai-experiments/tree/master/pcl-projection-rgb#installation , it seems that open3d is not supported on pi. Maybe the Luxonis team (or directly open3d developers) could give you more information about the support.

**Comment by wb666greene** [comment]
Seems you need to reboot after running the pip install of requirements.txt.

If that doesn't work what does:
glxinfo | grep "OpenGL version"
return?

I had similar on Ubuntu 20.04 on an i7 system, while searching for fixing GLFW errors, It looks like it should work on the Pi4, at least version 3.1

Maybe this is a place to start:
https://www.raspberrypi.org/forums/viewtopic.php?t=222264

**Comment by geaxgx** [comment]
No more activity on this thread. Closing.
